-- H2数据库测试用表结构

-- 1. 创建下拉列表值表
CREATE TABLE auth_lookup_value (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_code VARCHAR(50) NOT NULL,
    item_value VARCHAR(200) NOT NULL,
    label VARCHAR(200) NOT NULL,
    parent_id BIGINT,
    sort_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. 创建授权书主表
CREATE TABLE auth_letter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    auth_target_level VARCHAR(500),
    applicable_region VARCHAR(1000),
    auth_publish_level VARCHAR(500),
    auth_publish_org VARCHAR(1000),
    publish_year INTEGER,
    summary VARCHAR(4000),
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    created_by VARCHAR(100),
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100),
    updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. 创建附件表
CREATE TABLE auth_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    letter_id BIGINT NOT NULL,
    doc_name VARCHAR(500) NOT NULL,
    doc_type VARCHAR(50),
    doc_id VARCHAR(200),
    is_encrypted BOOLEAN DEFAULT FALSE,
    created_by VARCHAR(100),
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100),
    updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. 创建场景表
CREATE TABLE auth_scene (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    letter_id BIGINT NOT NULL,
    scene_name VARCHAR(200) NOT NULL,
    industry VARCHAR(1000),
    business_scene VARCHAR(200),
    decision_level VARCHAR(200),
    specific_rule VARCHAR(1000),
    rule_config CLOB,
    created_by VARCHAR(100),
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100),
    updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. 创建规则参数配置表
CREATE TABLE auth_rule_param (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    name_en VARCHAR(200),
    business_objects CLOB,
    value_logics CLOB,
    is_active BOOLEAN DEFAULT TRUE,
    data_type VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_by VARCHAR(100),
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100),
    updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. 创建操作日志表
CREATE TABLE auth_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    letter_id BIGINT NOT NULL,
    operation VARCHAR(200) NOT NULL,
    operator VARCHAR(100),
    operation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);